INSERT INTO car (
    id,
    mileage,
    doors,
    year,
    discount,
    price,
    price_after_discount,
    is_discounted,
    make,
    model,
    body,
    engine_size,
    fuel_type,
    is_registered,
    img_src,
    extra,
    registration,
    transmission_type,
    is_sold
) VALUES (
    1,
    13900,
    2,
    2019,
    12,
    162748,
    142950,
    true,
    'Bentley',
    'Continental GT',
    'Coupe',
    '6L W12',
    'Petrol',
    false,
    'https://lkswebprdcdnep4.azureedge.net:443/api/image/stock/f6fb5a5e-3b9c-4847-aabf-2e5fd9a6af4c?size=1024x768&quality=80',
    'First Edition',
    'NEW (In Stock)',
    'Automatic',
    false
);
